version: '2.1'
services:
    redis:
        image: 'redis:3.2.7'
        # command: redis-server --requirepass redispass

    webserver:
        build:
            args:
                - GIT_KEY=${GIT_KEY}
            context: ./
            dockerfile: ./Dockerfile
        restart: always
        image: puckel/docker-airflow:1.9.0-2
        restart: always
        depends_on:
            - redis
        environment:
            - LOAD_EX=n
            - GIT_KEY=${GIT_KEY}
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=Celery
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PRIEST_GIT_URL=${PRIEST_GIT_URL}
            - PRIEST_GIT_BRANCH=${PRIEST_GIT_BRANCH}
        volumes:
            - ./shared:/usr/local/airflow/shared
            - /tmp:/tmp
        tmpfs:
          - /run
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        build:
            args:
                - GIT_KEY=${GIT_KEY}
            context: ./
            dockerfile: ./Dockerfile
        restart: always
        depends_on:
            - redis
        tmpfs:
          - /run
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build:
            args:
                - GIT_KEY=${GIT_KEY}
            context: ./
            dockerfile: ./Dockerfile
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./shared:/usr/local/airflow/shared
            - /tmp:/tmp
        tmpfs:
          - /run
        environment:
            - LOAD_EX=n
            - GIT_KEY=${GIT_KEY}
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=Celery
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PRIEST_GIT_URL=${PRIEST_GIT_URL}
            - PRIEST_GIT_BRANCH=${PRIEST_GIT_BRANCH}
        command: scheduler

    worker:
        build:
            args:
                - GIT_KEY=${GIT_KEY}
            context: ./
            dockerfile: ./Dockerfile
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./shared:/usr/local/airflow/shared
            - /tmp:/tmp
        tmpfs:
          - /run
        environment:
            - LOAD_EX=n
            - GIT_KEY=${GIT_KEY}
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=Celery
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PRIEST_GIT_URL=${PRIEST_GIT_URL}
            - PRIEST_GIT_BRANCH=${PRIEST_GIT_BRANCH}
        command: worker
